export const postsConstants = {
    GET_POSTS_REQUEST: "GET_POSTS_REQUEST",
    GET_POSTS_SUCCESS: "GET_POSTS_SUCCESS",
    GET_POSTS_FAILURE: "GET_POSTS_FAILURE",
    DELETE_POSTS_REQUEST: "DELETE_POSTS_REQUEST",
    DELETE_POSTS_SUCCESS: "DELETE_POSTS_SUCCESS",
    DELETE_POSTS_FAILURE: "DELETE_POSTS_FAILURE",
}